export const FRAME_DATA = [
  {
    id: 0,
    character: "Ryu",
    move: "2MK",
    advantage: -6,
    // image: require("@/assets/images/charAttacks/SF6_Ryu_5lk.png"),
    isAd: false,
    video: require("@/assets/video/2MK.mov"),
  },
  {
    id: 1,
    character: "Ryu",
    move: "2MK",
    advantage: -6,
    isAd: false,
    video: require("@/assets/video/2MK_2.mov"),
  },
  {
    id: 2,
    character: "Ryu",
    move: "2MK",
    advantage: -6,
    isAd: false,
    video: require("@/assets/video/2MK_copy.mov"),
  },
  {
    id: 3,
    character: "Ryu",
    move: "236HK",
    advantage: 3, // varies from -3 to +3
    // image: require("@/assets/images/charAttacks/SF6_Ryu_5lk.png"),
    isAd: false,
    video: require("@/assets/video/236HK.mov"),
  },
  {
    id: 4,
    character: "Ryu",
    move: "5LK",
    advantage: -4,
    // image: require("@/assets/images/charAttacks/SF6_Ryu_5lk.png"),
    isAd: false,
    video: require("@/assets/video/5LK.mov"),
  },
  {
    id: 5,
    character: "foo",
    move: "bar",
    advantage: 0,
    isAd: true,
    video: require("@/assets/video/placeholderAd_2.mov"),
  },
  // {
  //   id: 3,
  //   character: "Ryu",
  //   move: "5HK",
  //   advantage: 1, // on block the defender is 1
  //   image: require("@/assets/images/charAttacks/SF6_Ryu_5hk.png"),
  // },
  // {
  //   id: 4,
  //   character: "Ryu",
  //   move: "5HP",
  //   advantage: -2,
  //   image: require("@/assets/images/charAttacks/SF6_Ryu_5hp.png"),
  // },
  // {
  //   id: 5,
  //   character: "Ryu",
  //   move: "5LP",
  //   advantage: -1,
  //   image: require("@/assets/images/charAttacks/SF6_Ryu_5lp.png"),
  // },
  // {
  //   id: 6,
  //   character: "Ryu",
  //   move: "5MP",
  //   advantage: -1,
  //   image: require("@/assets/images/charAttacks/SF6_Ryu_5mp.png"),
  // },
];
